export const products = [
    {
        id: 1,
        name: "Triple Rock - Plaster of Paris(POP)",
        slug: "triple-rock---plaster-of-paris(pop)",
        productName: "Triple Rock - Plaster of Paris(POP)",
        description:
            "High-quality brown coat made from durable materials to keep you warm and stylish in any season.",
        categories: ["Home Decor", "House Decoration"],
        price: 2999.99,
        discountedPrice: 119.25,
        discount: 25,
        rating: 4.5,
        reviews: 45,
        images: [
            "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmFzaGlvbiUyMG1vZGVsfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D",
            "https://images.unsplash.com/photo-1512101903502-7eb0c9022c74?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D",
            "https://images.unsplash.com/photo-1496217590455-aa63a8350eea?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        ],
        features: [
            "Premium wool blend material",
            "Double-breasted button closure",
            "Adjustable waist belt",
            "Inner pocket for phone storage",
            "Wind-resistant and water-repellent",
        ],
        specifications: {
            Material: "Wool blend",
            Weight: "1.2 lbs",
            Dimensions: 'Shoulder: 18", Sleeve: 24", Length: 40"',
            AvailableSizes: ["S", "M", "L", "XL"],
            Color: "Brown",
            CareInstructions: "Dry clean only",
        },
        seller: {
            name: "Fashion Boutique",
            rating: 4.6,
            totalSales: 3200,
            joinedDate: "2021-08-12",
            location: "Los Angeles, CA",
        },
        estimatedDelivery: "3-7 business days",
        returnPolicy: "14-day return with original receipt",
    },
    {
        id: 1,
        slug: 'brown-coat',
        productName: 'Brown Coat',
        description: 'High-quality brown coat made from durable materials to keep you warm and stylish in any season.',
        price: 159.00,
        discountedPrice: 119.25,
        discount: 25,
        rating: 4.5,
        reviews: 45,
        images: [
            'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmFzaGlvbiUyMG1vZGVsfGVufDB8fDB8fHww',
            'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D',
            'https://images.unsplash.com/photo-1512101903502-7eb0c9022c74?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D',
            'https://images.unsplash.com/photo-1496217590455-aa63a8350eea?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
        features: [
            'Premium wool blend material',
            'Double-breasted button closure',
            'Adjustable waist belt',
            'Inner pocket for phone storage',
            'Wind-resistant and water-repellent',
        ],
        specifications: {
            Material: 'Wool blend',
            Weight: '1.2 lbs',
            Dimensions: 'Shoulder: 18", Sleeve: 24", Length: 40"',
            AvailableSizes: ['S', 'M', 'L', 'XL'],
            Color: 'Brown',
            CareInstructions: 'Dry clean only',
        },
        seller: {
            name: 'Fashion Boutique',
            rating: 4.6,
            totalSales: 3200,
            joinedDate: '2021-08-12',
            location: 'Los Angeles, CA',
        },
        estimatedDelivery: '3-7 business days',
        returnPolicy: '14-day return with original receipt',
    },
    {
        id: 2,
        slug: 'sweat-outfit-1',
        productName: 'Sweat Outfit - Gray',
        description: 'Comfortable gray sweat outfit perfect for lounging and casual wear, made with soft and breathable fabric.',
        price: 129.00,
        discountedPrice: 96.75,
        discount: 25,
        rating: 4.2,
        reviews: 60,
        images: [
            'https://images.unsplash.com/photo-1512101903502-7eb0c9022c74?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D',
            'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmFzaGlvbiUyMG1vZGVsfGVufDB8fDB8fHww',
        ],
        features: [
            'Soft cotton-polyester blend',
            'Elastic waistband and cuffs',
            'Breathable and lightweight',
            'Machine washable',
            'Available in multiple colors',
        ],
        specifications: {
            Material: 'Cotton-Polyester Blend',
            Weight: '0.8 lbs',
            Sizes: ['S', 'M', 'L', 'XL'],
            Colors: ['Gray'],
            CareInstructions: 'Machine wash cold, tumble dry low',
        },
        seller: {
            name: 'Comfy Apparel',
            rating: 4.7,
            totalSales: 5400,
            joinedDate: '2020-06-15',
            location: 'Chicago, IL',
        },
        estimatedDelivery: '2-5 business days',
        returnPolicy: '30-day return policy',
    },
    {
        id: 3,
        slug: 'sweat-outfit-2',
        productName: 'Sweat Outfit - Black',
        description: 'Versatile black sweat outfit with a comfortable fit, ideal for both workouts and lounging.',
        price: 129.00,
        discountedPrice: 96.75,
        discount: 25,
        rating: 4.3,
        reviews: 70,
        images: [
            'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D',
            'https://images.unsplash.com/photo-1496217590455-aa63a8350eea?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
        features: [
            'Durable cotton-polyester material',
            'Drawstring waist for a custom fit',
            'Moisture-wicking fabric',
            'Machine washable',
            'Breathable design suitable for workouts',
        ],
        specifications: {
            Material: 'Cotton-Polyester Blend',
            Weight: '0.9 lbs',
            Sizes: ['S', 'M', 'L', 'XL'],
            Colors: ['Black'],
            CareInstructions: 'Machine wash cold, air dry',
        },
        seller: {
            name: 'Athletic Essentials',
            rating: 4.8,
            totalSales: 6200,
            joinedDate: '2019-02-10',
            location: 'New York, NY',
        },
        estimatedDelivery: '3-6 business days',
        returnPolicy: 'Free returns within 14 days',
    },
    {
        id: 4,
        slug: 'sweat-outfit-3',
        productName: 'Sweat Outfit - Blue',
        description: 'Stylish blue sweat outfit made from premium materials, ensuring both comfort and durability.',
        price: 129.00,
        discountedPrice: 96.75,
        discount: 25,
        rating: 4.4,
        reviews: 55,
        images: [
            'https://images.unsplash.com/photo-1496217590455-aa63a8350eea?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1512101903502-7eb0c9022c74?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D',
        ],
        features: [
            'High-quality cotton blend',
            'Stylish crew neck design',
            'Comfortable fit for all-day wear',
            'Machine washable',
            'Available in trendy colors',
        ],
        specifications: {
            Material: 'Cotton Blend',
            Weight: '0.85 lbs',
            Sizes: ['S', 'M', 'L', 'XL'],
            Colors: ['Blue'],
            CareInstructions: 'Machine wash cold, hang dry',
        },
        seller: {
            name: 'Urban Comfort',
            rating: 4.6,
            totalSales: 4800,
            joinedDate: '2021-03-05',
            location: 'Seattle, WA',
        },
        estimatedDelivery: '2-4 business days',
        returnPolicy: 'Full refund within 30 days if unsatisfied',
    },

]
export const relatedProducts = [
    {
        id: 1,
        name: "Adjustable Standing Desk",
        price: 299.99,
        rating: 4.5,
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: 2,
        name: "Ergonomic Keyboard",
        price: 79.99,
        rating: 4.3,
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: 3,
        name: "Anti-Fatigue Mat",
        price: 39.99,
        rating: 4.6,
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D",
    },
    {
        id: 4,
        name: "Monitor Arm",
        price: 89.99,
        rating: 4.4,
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D",
    },
];